"""Pydantic data contracts / schemas module."""
from app.schemas.health import HealthCheckResponse, DatabaseStatus
from app.schemas.auth import (
    UserBase,
    UserCreate,
    UserUpdate,
    UserResponse,
    LoginRequest,
    Token,
    TokenPayload,
)
from app.schemas.fleet import (
    HubBase,
    HubCreate,
    HubUpdate,
    HubResponse,
    VehicleBase,
    VehicleCreate,
    VehicleUpdate,
    VehicleResponse,
    DriverBase,
    DriverCreate,
    DriverUpdate,
    DriverResponse,
    FleetOverviewResponse,
)

__all__ = [
    "HealthCheckResponse",
    "DatabaseStatus",
    "UserBase",
    "UserCreate",
    "UserUpdate",
    "UserResponse",
    "LoginRequest",
    "Token",
    "TokenPayload",
    "HubBase",
    "HubCreate",
    "HubUpdate",
    "HubResponse",
    "VehicleBase",
    "VehicleCreate",
    "VehicleUpdate",
    "VehicleResponse",
    "DriverBase",
    "DriverCreate",
    "DriverUpdate",
    "DriverResponse",
    "FleetOverviewResponse",
]
